import type { PublicSearchItem } from './PublicSearchDialog';

export const PUBLIC_SEARCH_ITEMS: PublicSearchItem[] = [
  { title: 'Dashboard & Control Ejecutivo', category: 'Producto', path: '/producto/dashboard', desc: 'Semáforo de alertas, deal rotting, pipeline ponderado y Copilot IA' },
  { title: 'CRM 360° Comercial', category: 'Producto', path: '/clientum-crm', desc: 'Pipeline Kanban, gestión de tratos y forecast' },
  { title: 'WhatsApp Multiagente & Baileys', category: 'Producto', path: '/producto/whatsapp-ia', desc: 'Centraliza números comerciales con QR' },
  { title: 'Facturación AFIP con CAE', category: 'Fiscal & ERP', path: '/producto/erp', desc: 'Facturas A, B, C automáticas con QR fiscal' },
  { title: 'Agente OS Autónomo (Gemini 3.7)', category: 'Inteligencia Artificial', path: '/producto/agentes-ia', desc: '14 roles IA para ventas, soporte y finanzas' },
  { title: 'Planes y Precios', category: 'Comercial', path: '/precios', desc: 'Tarifas transparentes en ARS y USD' },
  { title: 'Casos de Éxito por Industria (14 Proyectos)', category: 'Empresa', path: '/casos', desc: 'Morgado Hogar, Farmacia San Martín, Terbay, Forestal Norte y más' },
  { title: 'Programa de Alianzas & Afiliados', category: 'Partners', path: '/alianzas', desc: '30% de comisión recurrente y canal de partners de implementación' },
  { title: 'Trabajá con Nosotros (Búsquedas Abiertas)', category: 'Carreras', path: '/trabajo', desc: 'Posiciones remotas para devs, consultores, ventas y diseño UI/UX' },
  { title: 'Academia LMS & Certificaciones', category: 'Educación', path: '/academia', desc: 'Cursos interactivos con diploma digital' },
  { title: 'Agroindustria & Acopios', category: 'Industrias', path: '/industrias/agro', desc: 'Solución para maquinaria, insumos y acopios' },
  { title: 'Distribuidoras Mayoristas', category: 'Industrias', path: '/industrias/distribuidoras', desc: 'Ventas por volumen, listas de precios y logística' },
  { title: 'Estudios Contables & Jurídicos', category: 'Industrias', path: '/industrias/estudios-contables', desc: 'Gestión masiva de clientes y AFIP' },
  { title: 'Salud & Clínicas Médicas', category: 'Industrias', path: '/industrias/salud', desc: 'Turnos automáticos y recordatorios de citas' },
  { title: 'Inmobiliarias & Desarrollos', category: 'Industrias', path: '/industrias/inmobiliaria', desc: 'Tasaciones, propiedades y contratos' },
  { title: 'Tienda Digital Oficial', category: 'Herramientas', path: '/tienda/central', desc: 'Catálogo público con cotización y checkout' },
  { title: 'Gestor de Dominios & DNS Cloudflare', category: 'Herramientas', path: '/dominios', desc: 'Zona DNS, SSL y auditoría SEO On-Page' },
  { title: 'Servicios Profesionales de Migración', category: 'Servicios', path: '/servicios', desc: 'Puesta en marcha e integración llave en mano' },
  { title: 'Auditoría Express de Madurez Digital', category: 'Diagnóstico', path: '/auditoria-express', desc: 'Diagnóstico gratuito de 6 preguntas con score y recomendaciones en 2 minutos' },
  { title: 'Brochure Corporativo & Ficha Técnica', category: 'Empresa', path: '/brochure', desc: 'Documento institucional descargable con arquitectura, SLA y trayectoria' },
  { title: 'Organigrama & Sedes Regionales', category: 'Empresa', path: '/organigrama', desc: 'Estructura directiva, oficinas en Patagonia y Rosario, y gobierno corporativo' },
  { title: 'Landing CRM + WhatsApp IA', category: 'Producto', path: '/crm-whatsapp-ia', desc: 'Página especializada en integración oficial de WhatsApp y CRM con simulador' },
  { title: 'Proyectos Destacados & Portfolio', category: 'Casos', path: '/proyectos', desc: 'Implementaciones clave en Maps B2B, Agro ERP, E-Commerce y Streaming PWA' },
  { title: 'Cotizador Interactivo de Proyectos', category: 'Comercial', path: '/cotizador', desc: 'Calcula tu presupuesto a medida en pesos argentinos o dólares' },
  { title: 'Contacto & Agendar Demostración', category: 'Contacto', path: '/contacto', desc: 'Habla con un consultor comercial sénior' },
];